### ISSUE TITLE
Make search case insensive

### ISSUE THREAD

**Issue by feklee** [Zero3/windows-installer-file-search#1]
Currently case needs to match perfectly, which shouldn’t be necessary as the Windows file systems are case insensitive.

**Comment by Zero3** [comment]
Thanks for the suggestion @feklee! I've changed the comparison to be case-insensitive as suggested (https://github.com/Zero3/windows-installer-file-search/commit/3908151652d692168433cb8ecb524394923e0fb4).

On a related note, I've also just added support for 32-bit Python on 64-bit Windows since I just noticed that this was broken (https://github.com/Zero3/windows-installer-file-search/commit/6f840d21bfda3d598d20b4ee9e75fe6c09614505).

**Comment by feklee** [comment]
Awesome, thanks!
